name: Dissector builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          sudo apt install -y build-essential wireshark-dev cmake
          mkdir build
          cd build
          cmake ..
          make
