name: Release latest snapshot for Linux

# https://github.com/marketplace/actions/upload-files-to-a-github-release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install -y build-essential wireshark wireshark-dev cmake
          # it's cleaner when we don't build it direcly in the source dir - let's create a separate one
          mkdir build
          cd build
          cmake ..
          make
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hazelcast.so
          tag: latest-snapshot
          overwrite: true
