name: Publish latest snapshot

# https://github.com/marketplace/actions/upload-files-to-a-github-release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install -y build-essential wireshark wireshark-dev cmake
          mkdir build
          cd build
          cmake ..
          make
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hazelcast.so
          tag: latest-snapshot
          overwrite: true
